### PR TITLE
move protocolDecoder stuff from aedes to this plugin

### PR DESCRIPTION
**Pull request by getlarge**
Here is the separated module.

### CODE REVIEW

**Comment by robertsLando** [comment]
@getlarge Thanks! Please add `pakage-lock.json` to `.gitignore`

**Comment by robertsLando** [comment]
Also rename `test/connect` in `test.js` and leave it to root folder

**Comment by robertsLando** [comment]
Take a look here for CI (it's as simple as copy and paste it with same folder structure) https://github.com/moscajs/aedes-persistence

Remeber to add the scripts to package.json, `nyc` and `license-checker` as dev dependencies

**Comment by getlarge** [comment]
Sure, i forgot about the docs, i will explain how to use it and make a link to aedes/examples/proxy, unless the example should be moved here ?
I will check how to add CI too.

**Comment by mcollina** [comment]
I would move the example here, and add an link from aedes.
Il 31 gen 2020, 10:35 +0100, getlarge <notifications@github.com>, ha scritto:

**Comment by getlarge** [comment]
It's done,  but there is an issue in the CI with Coveralls Parallel step.
It works for Node v.10, but not the others, do you any idea why ?
The error message is 
`
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
`

**Comment by robertsLando** [comment]
I have enabled it on coveralls.io, someone knows why this happen?

**Comment by getlarge** [comment]
It was enabled for moscajs repos ?
Maybe it didn't work in the context of my repo?

**Comment by robertsLando** [comment]
@getlarge 

Schermata da 2020-01-31 14-11-35

**Comment by getlarge** [comment]
@robertsLando But when i push it's on getlarge/aedes-protocol-decoder.
I tried again and the same error is triggered.

**Comment by getlarge** [comment]
I see that i in aedes repo, there is .coveralls.yml, could it be used for the Coveralls Parallel step?

**Comment by robertsLando** [comment]
@getlarge We are moving to codecov now

**Comment by robertsLando** [comment]
@getlarge I merge this for now to check if once merged checks work

**Pull request merged**
