### PR TITLE
fix: type issue

### PR DESCRIPTION
**Pull request by getlarge**
Fix a small issue when using this lib in a TS project.

### CODE REVIEW

**Review by GavinDmello — APPROVED** [review]

**Review by robertsLando — APPROVED** [review]
LGTM

**Comment by robertsLando** [comment]
@getlarge Would you make a new patch release?

**Comment by getlarge** [comment]
@robertsLando Yes, let's see if i can now!

**Comment by getlarge** [comment]
Still get this `User getlarge is not a collaborator for aedes-protocol-decoder`, do i need an access token with specific scopes to be able to publish package for Mosca org ?

**Comment by getlarge** [comment]
Btw, i don't see the aedes-protocol-decoder package in the Mosca org in npm, so maybe i just don't have access to it ?

**Comment by robertsLando** [comment]
@getlarge Are you sure? I see you should have write access to it, also you published the last version right?

**Comment by getlarge** [comment]
@robertsLando I published the latest version of aedes-server-factory (for which i can also access the settings in npm), but not for this one.

**Comment by robertsLando** [comment]
@getlarge Oh sorry I was looking for aedes-server factory

**Comment by robertsLando** [comment]
@getlarge try now

**Comment by getlarge** [comment]
@robertsLando that worked, thanks.

**Pull request merged**
